FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD mysqlmaster
ENV MYSQL_DATABASE database
ENV MYSQL_USER mysql
ENV MYSQL_PASSWORD mysql
#ENV MYSQL_HOST=127.0.0.1
#ENV MYSQL_HOST=localhost


#ADD load_table.sql /docker-entrypoint-initdb.d

EXPOSE 3306